apiVersion: v1
kind: Service
metadata:
  name: weather-fix-service-loadbalancer-80
spec:
  type: LoadBalancer
  selector:
    app: weather-fix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: weather-fix
  name: weather-fix
spec:
  containers:
  - image: chrisley75/weather-fix:0.0.1
    name: weather-fix
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
