apiVersion: v1
kind: Service
metadata:
  name: weather-service-loadbalancer-80
spec:
  type: LoadBalancer
  selector:
    app: weather-alpine 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
